// Mocks generated by Mockito 5.4.2 from annotations
// in walippe/test/src/views/screens/create_group_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:walippe/src/drift/walippe_db.dart' as _i2;
import 'package:walippe/src/models/group_data.dart' as _i5;
import 'package:walippe/src/repositories/group_repository.dart' as _i3;
import 'package:walippe/src/views/form_validator.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWalippeDatabase_0 extends _i1.SmartFake
    implements _i2.WalippeDatabase {
  _FakeWalippeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i3.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WalippeDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeWalippeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.WalippeDatabase);
  @override
  _i4.Future<List<_i5.GroupData>> fetchGroups() => (super.noSuchMethod(
        Invocation.method(
          #fetchGroups,
          [],
        ),
        returnValue: _i4.Future<List<_i5.GroupData>>.value(<_i5.GroupData>[]),
      ) as _i4.Future<List<_i5.GroupData>>);
  @override
  _i4.Future<int> addGroupByString(
    String? name,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGroupByString,
          [
            name,
            description,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<void> deleteGroupById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteGroupById,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FormValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormValidator extends _i1.Mock implements _i6.FormValidator {
  MockFormValidator() {
    _i1.throwOnMissingStub(this);
  }
}
